// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push/push_message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class NotifyMessage;
GPB_ENUM_FWD_DECLARE(ErrCode);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PushMessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PushMessageRoot : GPBRootObject
@end

#pragma mark - SendMessageRequest

typedef GPB_ENUM(SendMessageRequest_FieldNumber) {
  SendMessageRequest_FieldNumber_ConnIdListArray = 1,
  SendMessageRequest_FieldNumber_Mid = 2,
  SendMessageRequest_FieldNumber_Msg = 3,
  SendMessageRequest_FieldNumber_IsBroadcast = 4,
  SendMessageRequest_FieldNumber_CacheType = 5,
  SendMessageRequest_FieldNumber_Timestamp = 6,
};

@interface SendMessageRequest : GPBMessage

/** 需要发送到的目的connidlist */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *connIdListArray;
/** The number of items in @c connIdListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger connIdListArray_Count;

@property(nonatomic, readwrite) uint64_t mid;

@property(nonatomic, readwrite) BOOL hasMid;
@property(nonatomic, readwrite, strong, null_resettable) NotifyMessage *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@property(nonatomic, readwrite) uint32_t isBroadcast;

@property(nonatomic, readwrite) BOOL hasIsBroadcast;
/** 0:不用缓存 1: 缓存最新 */
@property(nonatomic, readwrite) uint32_t cacheType;

@property(nonatomic, readwrite) BOOL hasCacheType;
/** 消息过期时间戳 */
@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@end

#pragma mark - SendMessageResponse

typedef GPB_ENUM(SendMessageResponse_FieldNumber) {
  SendMessageResponse_FieldNumber_ErrCode = 1,
};

@interface SendMessageResponse : GPBMessage

@property(nonatomic, readwrite) enum ErrCode errCode;

@property(nonatomic, readwrite) BOOL hasErrCode;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
