// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router/heartbeat.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(ErrCode);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HeartbeatRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HeartbeatRoot : GPBRootObject
@end

#pragma mark - HeartbeatRequest

typedef GPB_ENUM(HeartbeatRequest_FieldNumber) {
  HeartbeatRequest_FieldNumber_ConnNum = 1,
  HeartbeatRequest_FieldNumber_SlotsArray = 2,
  HeartbeatRequest_FieldNumber_Host = 3,
  HeartbeatRequest_FieldNumber_Port = 4,
};

@interface HeartbeatRequest : GPBMessage

@property(nonatomic, readwrite) uint32_t connNum;

@property(nonatomic, readwrite) BOOL hasConnNum;
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *slotsArray;
/** The number of items in @c slotsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger slotsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *host;
/** Test to see if @c host has been set. */
@property(nonatomic, readwrite) BOOL hasHost;

@property(nonatomic, readwrite) int32_t port;

@property(nonatomic, readwrite) BOOL hasPort;
@end

#pragma mark - HeartbeatResponse

typedef GPB_ENUM(HeartbeatResponse_FieldNumber) {
  HeartbeatResponse_FieldNumber_ErrCode = 1,
};

@interface HeartbeatResponse : GPBMessage

@property(nonatomic, readwrite) enum ErrCode errCode;

@property(nonatomic, readwrite) BOOL hasErrCode;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
