// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router/slot_operate.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(ErrCode);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SlotOperateRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SlotOperateRoot : GPBRootObject
@end

#pragma mark - SlotOperationRequest

typedef GPB_ENUM(SlotOperationRequest_FieldNumber) {
  SlotOperationRequest_FieldNumber_SlotArray = 1,
  SlotOperationRequest_FieldNumber_OpType = 2,
};

@interface SlotOperationRequest : GPBMessage

/** 需要操作的slot */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *slotArray;
/** The number of items in @c slotArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger slotArray_Count;

/** 0:删除该slot, 1:增加该slot */
@property(nonatomic, readwrite) int32_t opType;

@property(nonatomic, readwrite) BOOL hasOpType;
@end

#pragma mark - SlotOperationResponse

typedef GPB_ENUM(SlotOperationResponse_FieldNumber) {
  SlotOperationResponse_FieldNumber_ErrCode = 1,
  SlotOperationResponse_FieldNumber_SlotArray = 2,
  SlotOperationResponse_FieldNumber_OpType = 3,
};

@interface SlotOperationResponse : GPBMessage

@property(nonatomic, readwrite) enum ErrCode errCode;

@property(nonatomic, readwrite) BOOL hasErrCode;
/** 操作完成的slot */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *slotArray;
/** The number of items in @c slotArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger slotArray_Count;

/** 同上 */
@property(nonatomic, readwrite) int32_t opType;

@property(nonatomic, readwrite) BOOL hasOpType;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
