// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: err_code.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "ErrCode.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ErrCodeRoot

@implementation ErrCodeRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - Enum ErrCode

GPBEnumDescriptor *ErrCode_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Ok\000IllegalRequest\000InvalidConnection\000Serv"
        "erTooBusy\000InternalErr\000ServerNotReady\000NoC"
        "ontent\000NoSeiyaServer\000";
    static const int32_t values[] = {
        ErrCode_Ok,
        ErrCode_IllegalRequest,
        ErrCode_InvalidConnection,
        ErrCode_ServerTooBusy,
        ErrCode_InternalErr,
        ErrCode_ServerNotReady,
        ErrCode_NoContent,
        ErrCode_NoSeiyaServer,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(ErrCode)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:ErrCode_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL ErrCode_IsValidValue(int32_t value__) {
  switch (value__) {
    case ErrCode_Ok:
    case ErrCode_IllegalRequest:
    case ErrCode_InvalidConnection:
    case ErrCode_ServerTooBusy:
    case ErrCode_InternalErr:
    case ErrCode_ServerNotReady:
    case ErrCode_NoContent:
    case ErrCode_NoSeiyaServer:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
