# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'news' do

pod 'AFNetworking',"2.6.3"
pod 'CocoaLumberjack',"~> 2.0.0"
pod 'JSONModel',"~> 1.0.2"
pod 'SDWebImage', '~>3.7.5'
pod 'CRGradientNavigationBar',"~> 0.3.2"
pod 'BlocksKit',"~> 2.2.5"
pod 'TPKeyboardAvoiding',"~> 1.2.6"
pod 'WebViewJavascriptBridge'
pod 'NJKWebViewProgress'
pod 'Masonry'
#pod 'Fabric'
#pod 'Crashlytics'
pod 'Bugly'
pod 'SSZipArchive'
pod 'MBProgressHUD'
pod 'VerifyCode'

end

