// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/connect.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(ErrCode);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ConnectRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ConnectRoot : GPBRootObject
@end

#pragma mark - ConnectRequest

typedef GPB_ENUM(ConnectRequest_FieldNumber) {
  ConnectRequest_FieldNumber_ConnId = 1,
  ConnectRequest_FieldNumber_Token = 2,
  ConnectRequest_FieldNumber_Sign = 3,
};

@interface ConnectRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *connId;
/** Test to see if @c connId has been set. */
@property(nonatomic, readwrite) BOOL hasConnId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;
/** Test to see if @c sign has been set. */
@property(nonatomic, readwrite) BOOL hasSign;

@end

#pragma mark - ConnectResponse

typedef GPB_ENUM(ConnectResponse_FieldNumber) {
  ConnectResponse_FieldNumber_ErrCode = 1,
};

@interface ConnectResponse : GPBMessage

@property(nonatomic, readwrite) enum ErrCode errCode;

@property(nonatomic, readwrite) BOOL hasErrCode;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
